# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/mkdocs-1.6.json
site_name: gRPC API Gateway
site_url: https://gopencloud.github.com/grpc-api-gateway
site_description: Documentation for the gRPC API Gateway (https://github.com/gopencloud/grpc-api-gateway).
repo_name: gopencloud/grpc-api-gateway
repo_url: https://github.com/gopencloud/grpc-api-gateway

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - tables
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: Â¶
  - pymdownx.snippets:
      base_path: "docs"

nav:
  - Getting started:
      - index.md
      - installation.md
  - Quickstart Demo:
      - quickstart/intro.md
      - quickstart/generation.md
      - quickstart/http_binding.md
      - quickstart/openapi.md
  - Reference:
      - reference/intro.md
      - reference/configuration.md
      - reference/example.md
      - Gateway:
          - reference/grpc/cli.md
          - reference/grpc/config.md
          - reference/grpc/query.md
          - reference/grpc/streaming.md
          - reference/grpc/errors.md
      - OpenAPI:
          - reference/openapi/cli.md
          - reference/openapi/patch.md
          - reference/openapi/field_optionality.md
          - reference/openapi/go_template.md
          - reference/openapi/operation_id.md
          - reference/openapi/visibility.md
          - reference/openapi/config.md

theme:
  name: material
  logo: assets/squid.png
  favicon: assets/squid.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - navigation.tabs
    - navigation.expand
    - navigation.tracking
    - content.tabs.link
    - content.code.copy
    - content.code.annotate

  palette:
    # Palette toggle for dark mode
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for light mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
